/********************************************************************************
** Copyright TOTVS S.A. (2015)
** Todos os Direitos Reservados.
**
** Este fonte e de propriedade exclusiva da TOTVS, sua reproducao
** parcial ou total por qualquer meio, so podera ser feita mediante
** autorizacao expressa.
********************************************************************************/

/********************************************************************************
** Programa.: Framework.cls
**
** Data.....: 28/10/2015
**
** Cria‡Æo..: Menna
**
** Objetivo.: Classe abstrata que devera ser herdada por todas as classes 
** utilitarias do framework.
********************************************************************************/

CLASS com.totvs.framework.Framework ABSTRACT:
END CLASS.
