ENUM com.totvs.framework.sec.scim.ErrorTypeEnum:
    DEFINE ENUM INVALID_FILTER = 0
                TOO_MANY       = 1
                UNIQUENESS     = 2
                MUTABILITY     = 3
                INVALID_SINTAX = 4
                INVALID_PATH   = 5
                NO_TARGET      = 6
                INVALID_VALUE  = 7
                INVALID_VERS   = 8
                SENSITIVE      = 9.
END ENUM.
