
/*------------------------------------------------------------------------
    File        : UserEmailType
    Purpose     : Enum com os tipos de e-mail conforme padrao SCIM
    Syntax      : 
    Description : Tipos de e-mail
    Author(s)   : rubens.santos
    Created     : Tue Jul 10 15:16:50 BRT 2018
    Notes       : 
  ----------------------------------------------------------------------*/

ENUM com.totvs.framework.sec.scim.UserEmailTypeEnum:  
    DEFINE ENUM WORK = 1
                HOME = 2
                OTHER = 3.
END ENUM.
